/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Console */

#ifndef _Included_org_saleen_util_log_Console
#define _Included_org_saleen_util_log_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org.saleen.util.log.Console
 * Method:    setTitleWindows
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_saleen_util_log_Console_setTitleWindows
  (JNIEnv *, jclass, jstring);
#ifdef __cplusplus
}
#endif
#endif